- aleo-setup1/src/bin/prepare_phase2.rs
- aleo-setup1/src/cli/contribute.rs
- aleo-setup1/src/cli/transform.rs
- aleo-setup2/src/cli/new.rs
- phase1/benches/phase1.rs
- phase1/src/computation.rs
- phase1/src/helpers/accumulator.rs
- phase1/src/helpers/buffers.rs
- phase1/src/helpers/testing.rs
- phase1/src/initialization.rs
- phase1/src/serialization.rs
- phase1/src/verification.rs
- phase1/tests/aleo_compatibility.rs
- phase2/src/keypair.rs
- phase2/src/parameters.rs
- phase2/tests/aleo_compatibility.rs
- setup-utils/src/elements.rs
- setup-utils/src/groth16_utils.rs
- setup-utils/src/io/mod.rs
- setup-utils/src/io/read.rs
- setup-utils/src/lib.rs
CheckForCorrectness checks whether an element is the infinity points when being read. This is important for verification, where pairings checks would silently pass instead of fail.
> feat: reintrocues CheckForCorrectness

- phase1/src/helpers/buffers.rs
Ratio verification between powers of tau previously only worked in the context of a chunk.
For example, if chunk 1 had (tau^2, tau^3, tau^4) and chunk 2 had (tau^10,tau^11,tau^12) - both chunks internally have the same ratio tau, but between the chunks the ratio is tau^6.
This PR ensures that the first element from the succeeding chunk is compared to the last element in the current chunk.
> fix: ensure overlap between chunks

- phase1-cli/src/bin/phase1.rs
- phase1-cli/src/contribute.rs
- phase1-cli/src/new_challenge.rs
- phase1-cli/src/transform_pok_and_correctness.rs
- phase1-cli/src/transform_ratios.rs
- phase1-coordinator/src/apis/chunk_get.rs
- phase1-coordinator/src/commands/aggregation.rs
- phase1-coordinator/src/commands/computation.rs
- phase1-coordinator/src/commands/initialization.rs
- phase1-coordinator/src/commands/verification.rs
- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/environment.rs
- phase1-coordinator/src/locators/local.rs
- phase1-coordinator/src/locators/locator.rs
- phase1-coordinator/src/locators/remote.rs
- phase1-coordinator/src/macros.rs
- phase1-coordinator/src/objects/round.rs
- phase1-coordinator/src/testing/resources/round.json
- phase1-coordinator/src/testing/resources/round_partial.json
- phase1-coordinator/src/testing/resources/test_round_0.json
- phase1-coordinator/src/testing/resources/test_round_1_initial.json
This PR introduces flexible and centralized support for compression modes in contributions and response, which are now controlled by the coordinator environment.
Additionally, it modifies contribution locators to include a "verified" status, to signify whether they're a challenge or a response. In a world where compression modes differ between inputs and outputs, one will contain a compressed version and the other an uncompressed one. If they're equal, they're mostly the same. In any case, the challenges do not contain the public key of the response.
> feat(coordinator): support different compression modes and adjust locators

- phase1-coordinator/src/apis/chunk_get.rs
- phase1-coordinator/src/commands/aggregation.rs
- phase1-coordinator/src/commands/computation.rs
- phase1-coordinator/src/commands/initialization.rs
- phase1-coordinator/src/commands/verification.rs
- phase1-coordinator/src/coordinator.rs
A strict precondition of `next_contribution_locator` is that the locator corresponding to the given round height, chunk ID, and contribution ID must not exist or be verified. To adhere to intended usage, this PR removes `verified` as an input argument to the method.
> Removes 'verified' from `next_contribution_locator` as it must always be false.

- phase1-coordinator/src/coordinator_state.rs
This PR fixes output of one of the ceremony status fields, adds an additional check for banned participants, and removes automatic dropping of verifiers.
> Coordinator cleanup

- phase1-coordinator/src/coordinator_state.rs
- phase1-coordinator/src/objects/round.rs
- phase1-coordinator/src/storage/disk.rs
- phase1-coordinator/src/tests.rs
With this change `coordinator_drop_multiple_contributors_test` now passes.
Affected tests which required an update:
The fix for task reallocation is described below. Say, we have 2 contributors, 2 buckets, 4 chunks in each bucket. When we make all contributions, the state is:
```
contributor1 assigned tasks length is 0
contributor1 completed tasks length is 8
contributor2 assigned tasks length is 0
contributor2 completed tasks length is 8
```
When we drop contributor 1, the state before the change would be
```
contributor2 assigned tasks length is 8
contributor2 completed tasks length is 0
contributor2 disposed tasks length is 4
```
After the change from this PR the state would be
```
contributor2 assigned tasks length is 4
contributor2 completed tasks length is 0
contributor2 disposed …
```
> Fix for the test with drop of multiple contributors

- Cargo.lock
Fix for a security vulnerability found by cargo-audit
https://rustsec.org/advisories/RUSTSEC-2020-0091
> Adresses security advisory about arc-swap

- phase1-coordinator/src/coordinator_state.rs
- phase1-coordinator/src/environment.rs
- phase1-coordinator/src/objects/participant.rs
- phase1-coordinator/src/objects/round.rs
Related to #156
Adresses only `.clone()`-related warnings
> Fixed clippy warnings related to redundant clone

- phase1-coordinator/src/tests.rs
Closes #124 
In this test all of the contributors are dropped and replaced with the coordinator contributors, then contributions & verifications are done and the round is updated to the next one.
> Test replace contributors and compete round

- Cargo.lock
- setup1-verifier/Cargo.toml
- setup1-verifier/src/lib.rs
Removed unused `failure` from `setup1-verifier`, also fixed some of the `cargo audit` warnings (mostly about yanked crates).
> Removed failure dependency, fixed some of the cargo audit warnings

- .github/workflows/cargo-audit.yml
- Cargo.lock
This pr adds `cargo audit` security check to our ci runs. It also updates `generic-array` dependency to fix the audit error. You can check the actions history to see that it actually fails when there are vulnerabilities.
Closes #153
> Cargo audit ci

- Cargo.lock
Updated `sharded-slab` crate to address https://rustsec.org/advisories/RUSTSEC-2020-0151
Originally I tried to do `cargo update -p generator` but the patched version mentioned in the advisory is `>=0.7.0`, while we had `0.6.23` in Cargo.lock, so `cargo update` is not helpful in this case.
Also updated `pin-project-lite` because old versions have been yanked
> Cargo audit fix 

- phase1-coordinator/Cargo.toml
- phase1-coordinator/README.md
- phase1-coordinator/src/logger.rs
- phase1-coordinator/src/testing/coordinator.rs
- phase1-coordinator/src/tests.rs
Two main changes here are:
- used `RUST_LOG` env variable to initialize logs in tests. Default log level is `error`
- removed `silent` feature. Use `RUST_LOG` instead to configure the log levels
As one of the benefits we no longer need to recompile the crate to hide the logs, just use the different level in `RUST_LOG`
Closes #238
> RUST_LOG env for tests

- Cargo.lock
- phase1-coordinator/Cargo.toml
- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/macros.rs
- phase1-coordinator/src/testing/prelude.rs
- phase1-coordinator/src/tests.rs
- Removed `test_report` macro and function
- Removed duplication of the word `test` in some test names, because default report already adds it:
```
test tests::round_on_groth16_bw6_761 ... ok
test tests::round_on_marlin_bls12_377 ... ok
test tests::try_lock_blocked ... ok
```
Closes #239
> Standard cargo report in tests

- phase1-coordinator/src/coordinator_state.rs
- phase1-coordinator/src/objects/round.rs
- phase1-coordinator/src/storage/storage.rs
- phase1-coordinator/src/tests.rs
A number of changes related to a drop contributor logic:
- Now locks for contribution file signatures are also cleared
- Verifier's completed tasks are now updated
- Initial challenge locator is not removed anymore
- Added two new tests, and changed one old test
Closes #232 
Closes #235
> Updates for replacement contributors

- phase1-coordinator/src/commands/aggregation.rs
- phase1-coordinator/src/commands/computation.rs
- phase1-coordinator/src/commands/initialization.rs
- phase1-coordinator/src/commands/verification.rs
- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/objects/round.rs
- phase1-coordinator/src/storage/disk.rs
- phase1-coordinator/src/storage/storage.rs
refactor the `storage::Locator` enum to increase code readability
> Refactor storage::Locator enum to reduce use of un-named tuple fypes/fields/variants

- phase1-coordinator/src/coordinator.rs
This PR removes the logger initialisation from the Operator initialize method. The motivation is to let the users of this library to set their own loggers. In particular, it will allow to filter away the logs from third party libraries such as hyper.
> Don't initialize the logger

- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/objects/chunk.rs
- phase1-coordinator/src/objects/contribution.rs
- phase1-coordinator/src/objects/round.rs
- phase1-coordinator/src/storage/disk.rs
- phase1-coordinator/src/storage/storage.rs
- phase1-coordinator/src/tests.rs
- setup1-contributor/src/commands/contribute.rs
Make use of storage locator paths more type safe with the use of a new LocatorPath wrapper type. In the future I'd like to reduce the use of this type in favour of `Locator` wherever possible, but for now this makes it much easier to keep track of it.
> Storage locator path refactor

- Cargo.lock
- setup1-contributor/src/reliability/bandwidth.rs
- setup1-contributor/src/reliability/cpu.rs
- setup1-contributor/src/reliability/latency.rs
- setup1-contributor/src/reliability/mod.rs
- setup1-shared/Cargo.toml
- setup1-shared/src/reliability/contributor.rs
- setup1-shared/src/reliability/coordinator.rs
- setup1-shared/src/reliability/message.rs
- setup1-shared/src/reliability/mod.rs
- Updated message structure in reliability checks to avoid extra copy when sending message from coordinator. It was possible to achieve by replacing enum with a structure containing two fields. First - `name` is an enum, second one - `data` is a vector of bytes. It allows to access `message.data` without matching on the whole message.
- Implemented manual message encoding/decoding instead of using serde. The reason was the huge overhead from the formats. For example, if serialize a structure containing 100Mb of data using MessagePack, the encoded size will be around 150Mb (and way more with JSON), which is not very convenient for measuring bandwidth. After this change the overhead is 20-30 bytes, because message format is the following:
`message name length (1 byte) | message name (256 …
> Updates for bandwidth measurements in reliability score check

- phase1-coordinator/src/environment.rs
Reduce the Inner SNARK power parameter to 2^19 from 2^20 based on optimizations made in snarkVM
> Reduce power parameter for Inner SNARK

- Cargo.lock
- phase1-coordinator/Cargo.toml
- phase1-coordinator/src/commands/aggregation.rs
- phase1-coordinator/src/commands/computation.rs
- phase1-coordinator/src/commands/initialization.rs
- phase1-coordinator/src/commands/mod.rs
- phase1-coordinator/src/commands/verification.rs
- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/coordinator_state.rs
- phase1-coordinator/src/environment.rs
- phase1-coordinator/src/main.rs
- phase1-coordinator/src/objects/round.rs
- phase1-coordinator/src/storage/storage.rs
- phase1-coordinator/src/testing/coordinator.rs
- phase1-coordinator/src/tests.rs
- setup1-contributor/src/commands/contribute.rs
Refactors in preparation for solution to #304 
+ Remove storage lock and coordinator state lock. Rely instead on Rust's mutability analysis and management, the library user is responsible for managing this.
+ Remove unnecessary box on signature.
+ Move the responsibility for shutdown signal handling to the library user and update example with tokio signal handling for shutdown.
This isn't the final solution, it was a big refactor in the end so I put it into its own pull request. Haven't run all the tests yet, and there is still a compile error in there, but the example coordinator `main.rs` runs.
> Refactors for Fix/304 manual restart fails

- Cargo.lock
- phase1-coordinator/Cargo.toml
- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/coordinator_state.rs
- phase1-coordinator/src/objects/round.rs
Fix for #304 . Changes based on top of #311 
+ Remove contributions/verification files that were created when locks were
taken and the locators initialized.
+ Some more tracing instrumentation.
+ Remove some unnecessary inlines.
+ Better logging for timeout drops.
> Fix #304 manual restart fails

- .github/workflows/cli.yml
- .github/workflows/core.yml
- .github/workflows/setup1-cli-tools.yml
- .github/workflows/setup1-contributor.yml
- .github/workflows/wasm.yml
Used "stable" instead of pinned version. This helps to stay up to date with toolchain version, for example 1.54 has been released recently
> Use stable toolchain in CI

- Cargo.lock
- setup1-contributor/Cargo.toml
- setup1-contributor/src/commands/contribute.rs
The chrono Duration was used in a following way:
```rust
Duration::seconds(DELAY_POLL_CEREMONY_SECS).to_std()?
```
and if you want to move this to a function which doesn't return Result, it'll become
```rust
.to_std().unwrap()
```
On the other side, Duration from std has `const fn` constructors which report errors in compile time instead of runtime
> Replaced chrono Duration with std Duration in setup1-contributor

- phase1-coordinator/src/environment.rs
- Added the ability to configure the number of verifiers in the same way as the contributors.
- I've noticed `#[inline]` and `.clone()` in the same function, so I removed both, because taking `self` by value is better
> Additional configuration for Environment

- Cargo.lock
- phase1-cli/Cargo.toml
- phase1-coordinator/Cargo.toml
- phase1/Cargo.toml
- phase2/Cargo.toml
- setup-utils/Cargo.toml
- setup-utils/src/helpers.rs
- setup1-cli-tools/Cargo.toml
- setup1-contributor/Cargo.toml
- setup1-shared/Cargo.toml
- setup1-verifier/Cargo.toml
- setup2/Cargo.toml
- `rustc_version` to 0.4
- `itertools` to 0.10
- `cfg-if` to 1.0
- `blake2` to 0.9
Updated the usage of blake2, it's also good to remove confusion between blake2 0.8 and 0.9 because there are a few renamed methods.
> Updated dependencies to match the versions used by snarkVM

- setup1-contributor/src/cli/commands/generate.rs
- setup1-contributor/src/setup_keys/mod.rs
We don't use address field in coordinator itself, but integration tests still rely on it, this PR adds it back.
Also updated the help message to address #292 
Closes #292
> Fix tests and update coordinator help message

- setup1-cli-tools/README.md
- setup1-cli-tools/src/public_key_extractor.rs
Updated `public-key-extractor` to handle the case when there's not address in keys file
> Updated public key extractor tool

- phase1-coordinator/src/objects/round.rs
- phase1-coordinator/src/tests.rs
Fixes #305
The PR also includes a test which isolates the specific failure case. It can be pasted into the master branch and ran, and there you can see it will fail, making it easy to verify that this PR solved the issue.
> Fix verifier stall by adding missing logic for deleting response files

- setup1-contributor/src/commands/contribute.rs
- setup1-contributor/src/setup_keys/confirmation_key.rs
- setup1-shared/src/structures.rs
Updated progress bar messages. Show the number of tasks only if the contributor is in the current round. If the contributor in the queue, show that it's in the queue
> Updated contributor progress bar

- Cargo.lock
- phase1-cli/Cargo.toml
- phase1-cli/src/transform_ratios.rs
- phase1-coordinator/Cargo.toml
- phase1-coordinator/src/storage/disk.rs
- phase1-coordinator/src/storage/storage.rs
- phase1-coordinator/src/testing/coordinator.rs
- phase1-coordinator/src/tests.rs
- setup1-contributor/Cargo.toml
- setup1-contributor/src/commands/contribute.rs
- setup1-contributor/src/commands/generate.rs
- setup1-contributor/src/setup_keys/confirmation_key.rs
- setup1-contributor/src/utils.rs
- setup1-verifier/Cargo.toml
- setup1-verifier/src/main.rs
- setup2/Cargo.toml
- setup2/src/cli/contribute.rs
- setup2/src/cli/new.rs
- setup2/src/cli/verify.rs
#368 refactor some key useages of `std::fs` to use `fs-err` instead for improved error messages. 
Please do not merge before #361 
TODO: fix an error compiling unit tests
> #368 use fs-err for improved error messages

- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/storage/disk.rs
The error was caused by immediately using the `get()` call when trying to see if the round height file had been created yet. This will log an error if the file is missing, and thus preceding it with an `exists()` call will silence this error.
Fixes #336
> Remove unnecessary errors related to getting round height in tests

- Cargo.lock
- setup1-contributor/src/commands/contribute.rs
This fixes a bug in which a contributor can be dropped
inadvertently during queueing or while waiting for work.
Fixes #398
> Initiate heartbeat before the work loop starts

- e2e_inner.sh
- e2e_outer.sh
- phase2/Cargo.toml
- phase2/src/keypair.rs
- phase2/src/parameters.rs
- setup-utils/Cargo.toml
- setup-utils/src/helpers.rs
- setup2/src/cli/new.rs
This PR fixes:
* RNG usage on phase2 
* replace old implementation by new hash_to_curve function
* update e2e scripts (tested locally): 
** e2e_inner.sh finished after 3 or 4 hours in total
** e2e_outer.sh got killed after several hours (10 hours just to prepare for phase2) while checking the result of preparation, see last prints: 
```  
before AHP: constraints: 415012
before PC checks: constraints: 451343
before PC combining commitments: constraints: 451343
before PC batch check: constraints: 496530
after PC batch check: constraints: 542162
before AHP: constraints: 565020
before PC checks: constraints: 601351
before PC combining commitments: constraints: 601351
before PC batch check: constraints: 646538
after PC batch check: constraints: 692170
./e2e_outer.sh: line 29: 597790 Killed …
```
> Phase2 requirements

- setup-utils/src/helpers.rs
In setup_utils we had a secure implementation of hash to curve. In a recent PR, we replaced it by the new implementation from snarkVM, but this change broke compatibility, then we are going to restore the previous version.
> Revert to old implementation of hash to curve

- phase1-coordinator/src/coordinator.rs
This will ensure the coordinator wont crash
if it has been accidentally turned off during aggregation.
> Delete existing round file if trying to aggregate

- phase1-coordinator/src/coordinator.rs
Removed the check if the contributor is the current contributor. This issue may require some additional changes though.
> Contributor status fix

- phase1-cli/README.md
- phase1-cli/src/lib.rs
Removes the old nightly doc features in favour of the stabilised `include_str!`. 
Opened against `master`, please advise if this isn't the correct branch.
> Fix included readme doc

- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/coordinator_state.rs
- phase1-coordinator/src/environment.rs
- phase1-coordinator/src/tests.rs
This PR introduces the logic required to move participants using different addresses from the same IP to the back of the queue by `0`ing the reliability score. 
There are a few details I am unsure of:
- Coordinator state in that new test (see todo).
- The drop logic and conditions for which we'd remove participants from the IP list.
- Does `ParticipantInfo` need to be updated in all the maps to reflect the reliability score change (also a todo)?
I'm also unsure of the current process with regards to staging/integration testing so if someone could weigh in on that, that would be much appreciated. 
Coordinator PR: https://github.com/AleoHQ/aleo-setup-coordinator/pull/152
> Feat: keep track of participant IPs

- Cargo.lock
- phase1-coordinator/Cargo.toml
- phase1-coordinator/src/commands/aggregation.rs
- phase1-coordinator/src/commands/verification.rs
- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/coordinator_state.rs
- phase1-coordinator/src/environment.rs
- phase1-coordinator/src/objects/round.rs
- phase1-coordinator/src/testing/coordinator.rs
- phase1-coordinator/src/testing/resources/round.json
- phase1-coordinator/src/testing/resources/test_round_0.json
- phase1-coordinator/src/testing/resources/test_round_1_initial.json
- phase1-coordinator/src/testing/resources/test_round_1_partial.json
- phase1-coordinator/src/tests.rs
Supersedes #434 for the `chrono` failure.
Drafted as the tests still need some fixing.
> Remove the dependency on `chrono`

- Cargo.lock
- setup-utils/Cargo.toml
- setup-utils/src/helpers.rs
Removes the dependency as it is currently unmaintained and replaces it with `sha2`. 
Supersedes #434.
> Remove the dependency on `rust-crypto`

- Cargo.lock
Yet another dependency PR... though this reduces the `cargo audit` output significantly as many dependencies have received a minor version bump.
This fixes the `generator` and `tokio` audit failures.
> Deps: run `cargo update`

- Cargo.lock
- phase1-coordinator/Cargo.toml
- phase1-coordinator/src/commands/aggregation.rs
- phase1-coordinator/src/commands/verification.rs
- phase1-coordinator/src/coordinator.rs
- phase1-coordinator/src/coordinator_state.rs
- phase1-coordinator/src/environment.rs
- phase1-coordinator/src/objects/round.rs
- phase1-coordinator/src/testing/coordinator.rs
- phase1-coordinator/src/testing/resources/round.json
- phase1-coordinator/src/testing/resources/test_round_0.json
- phase1-coordinator/src/testing/resources/test_round_1_initial.json
- phase1-coordinator/src/testing/resources/test_round_1_partial.json
- phase1-coordinator/src/tests.rs
Reverts AleoHQ/aleo-setup#446
Using `time` broke too much of the surrounding dependencies of the setup, so the simplest option right now is to revert it.
> Revert "Remove the dependency on `chrono`"

- Cargo.lock
- phase1-coordinator/src/environment.rs
- phase1-coordinator/src/macros.rs
- phase1-wasm/Cargo.toml
- phase1-wasm/src/contributor.rs
- phase1-wasm/src/errors.rs
- phase1-wasm/src/phase1.rs
- phase1-wasm/src/requests.rs
- phase1-wasm/src/structures.rs
- phase1-wasm/src/utils.rs
- phase1/src/lib.rs
- phase1/src/macros.rs
+ Implement requesting of the coordinator public settings for `phase1-wasm`, now there is a nice error message if you try running the browser with an unsupported setup. 
+ Support for development environment in `phase1-wasm` (browser testing runs very fast now!)
+ Refactor error handling in `phase1-wasm` to use `anyhow` more and reduce clutter.
+ Use the `console_log` crate for improved logging.
> phase1-wasm request coordinator public settings
