AleoHQ/aleo-setup

.github/workflows/ci.yml, aleo-snark-setup/src/cli/new.rs
=> Adds CI workflow

Cargo.lock, phase1/src/computation.rs, phase1/src/initialization.rs, setup-utils/Cargo.toml, setup-utils/src/lib.rs, setup-utils/src/rayon_cfg.rs
It has the same interface as the normal rayon, and calls the functions directly.
=> feat: adds a rayon_cfg shim that works both with parallel and without

e2e_inner.sh, e2e_outer.sh
These take a long time to run. I'm running them on a server now to verify they work e2e.
=> feat: adds e2e tests that work e2e on the inner and outer snarks

Cargo.lock, Cargo.toml, aleo-setup1/src/bin/phase1.rs, aleo-setup1/src/bin/prepare_phase2.rs, aleo-setup1/src/cli/mod.rs, aleo-setup1/src/lib.rs, aleo-setup2/Cargo.toml, aleo-setup2/src/cli/new.rs, phase1/Cargo.toml, phase1/src/computation.rs, phase1/src/helpers/accumulator.rs, phase1/src/helpers/buffers.rs, phase1/src/helpers/testing.rs, phase1/src/initialization.rs, phase1/src/lib.rs, phase1/src/objects/parameters.rs, phase1/src/serialization.rs, phase1/src/verification.rs, phase1/tests/aleo_compatibility.rs, phase1/tests/marlin.rs, phase2/Cargo.toml, phase2/src/parameters.rs, phase2/tests/aleo_compatibility.rs, setup-utils/src/groth16_utils.rs
The protocol is implemented as described here:  https://hackmd.io/glaJt8KuQE26WCoZ4wfFTw. It generates an SRS for SonicKZG10.
=> Adds Marlin mode

phase1-wasm/src/phase1.rs
=> close #83 - provide a way to initialize the console error panic hook

.github/workflows/cli.yml, .github/workflows/core.yml, phase1-coordinator/Cargo.toml, phase1-coordinator/src/testing/prelude.rs
Fix import and temporarily disable nightly CI
=> Fix import and temporarily disable nightly CI

phase1-coordinator/src/tests.rs
Updated the `coordinator_drop_multiple_contributors_test` to use 3 replacement contributors and uncommented assertions.
Fixes #127
=> Test task allocation for multiple replacement contributors

.github/workflows/cli.yml, .github/workflows/core.yml, .github/workflows/wasm.yml, phase1-coordinator/src/coordinator.rs
=> Removed panic hook rewrite

Cargo.lock
Adresses security advisory https://rustsec.org/advisories/RUSTSEC-2021-0003
Removes duplicates of parking_lot
=> Updated smallvec to address security advisory, removed duplicates of parking_lot

Cargo.lock, phase1-coordinator/Cargo.toml, phase1-coordinator/src/lib.rs, phase1-coordinator/src/testing/coordinator.rs, phase1-coordinator/src/testing/prelude.rs
=> Removed lazy_static and adjusted features

.github/workflows/core.yml
=> Close #180 disable code coverage CI github action.

Cargo.lock, setup1-contributor/Cargo.toml, setup1-contributor/src/main.rs
=> Fix #203 missing localization for setup1-contributor age dependency

setup1-contributor/README.md, setup1-contributor/src/commands/contribute.rs, setup1-verifier/src/main.rs
Contributor and verifier parts of api adjustment
=> Renamed contributor/settings to coordinator/settings

setup1-contributor/src/reliability/cpu.rs
Implementation of Proof of Work:
* TOTAL_SIZE=14 was chosen  so that it takes roughly 20 seconds in my laptop. We can calibrate it to increase the difficulty if necessary.
=> Implement Proof of Work

setup1-contributor/src/commands/contribute.rs, setup1-contributor/src/objects.rs, setup1-contributor/src/tasks.rs, setup1-verifier/src/coordinator_requests.rs, setup1-verifier/src/objects.rs, setup1-verifier/src/tasks.rs, setup1-verifier/src/verifier.rs
=> Update contributor/verifier code to use new upload/download semantics

Cargo.lock, setup1-contributor/src/commands/contribute.rs, setup1-contributor/src/errors.rs, setup1-contributor/src/tasks.rs, setup1-contributor/src/utils.rs
Fixed compiler warnings related to unused code. Let me know if any of the functions is still needed, I'll mark it `allow` instead.
=> Removed unused code in setup1-contributor

Cargo.lock, phase1-cli/Cargo.toml, phase1-coordinator/Cargo.toml, phase1-coordinator/src/coordinator.rs, phase1-wasm/Cargo.toml, phase1/Cargo.toml, phase1/tests/marlin.rs, phase2/Cargo.toml, setup-utils/Cargo.toml, setup1-cli-tools/Cargo.toml, setup1-cli-tools/src/public_key_extractor.rs, setup1-cli-tools/src/view_key.rs, setup1-contributor/Cargo.toml, setup1-contributor/src/commands/contribute.rs, setup1-contributor/src/reliability/mod.rs, setup1-contributor/src/setup_keys/mod.rs, setup1-contributor/src/utils.rs, setup1-verifier/Cargo.toml, setup1-verifier/src/coordinator_requests.rs, setup1-verifier/src/main.rs, setup1-verifier/src/utils/authentication.rs, setup1-verifier/src/verifier.rs, setup2/Cargo.toml, setup2/src/cli/new.rs
Update snarkvm revs that are pinned in Cargo.toml in setup1 contributor to account for updates in snarkVM private key generation logic
=> Update snarkvm dependency

Cargo.lock, setup1-contributor/Cargo.toml, setup1-contributor/src/commands/contribute.rs, setup1-shared/Cargo.toml, setup1-shared/src/structures.rs
=> Add attestation tweet prompt after eth address prompt

phase1-coordinator/src/environment.rs
change batch size for universal setup to speed aggregation
=> update batch size for universal setup

phase1-cli/Cargo.toml, phase1-coordinator/Cargo.toml, phase1-coordinator/src/environment.rs, phase1-wasm/Cargo.toml, phase1/Cargo.toml, phase2/Cargo.toml, setup1-verifier/Cargo.toml, setup2/Cargo.toml
Enabling default features, aiming for `parallel` to work. This is the one currently running in Coordinator 2 (the one *not* in the load balancer).
=> enabling default features, aiming for parallel

.github/workflows/core.yml, .github/workflows/setup1-contributor.yml, phase1-cli/Cargo.toml, phase1-cli/scripts/phase1_chunked.sh, phase1-cli/scripts/phase1_full.sh, phase1-coordinator/Cargo.toml, phase1-wasm/Cargo.toml, phase1/Cargo.toml, phase2/Cargo.toml, setup-utils/Cargo.toml, setup1-contributor/Cargo.toml, setup1-verifier/Cargo.toml, setup2/Cargo.toml
Update batch size and enable parallel features, to improve CPU and memory utilization in the Coordinator and Verifiers.
=> Update batch size and enable parallel features

Cargo.lock, phase1-cli/Cargo.toml, phase1-cli/src/contribute.rs
=> Log challenge/contribution hash information, instead of printing it

phase1-coordinator/src/coordinator.rs
=> Avoid coordinator panic when resetting with fractured disk state

Cargo.lock, setup1-contributor/Cargo.toml, setup1-contributor/src/reliability/cpu.rs, setup1-contributor/src/reliability/mod.rs, setup1-shared/Cargo.toml, setup1-shared/src/lib.rs, setup1-shared/src/proof_of_work.rs
Some updates to enable powers of tau cpu checks in the contributor
=> Enabled proof of work cpu checks

phase1-coordinator/src/commands/aggregation.rs, phase1-coordinator/src/commands/computation.rs, phase1-coordinator/src/commands/initialization.rs, phase1-coordinator/src/commands/mod.rs, phase1-coordinator/src/commands/verification.rs, phase1-coordinator/src/coordinator.rs, phase1-coordinator/src/coordinator_state.rs, phase1-coordinator/src/environment.rs, phase1-coordinator/src/main.rs, phase1-coordinator/src/objects/round.rs, phase1-coordinator/src/storage/disk.rs, phase1-coordinator/src/storage/storage.rs, phase1-coordinator/src/testing/coordinator.rs, phase1-coordinator/src/tests.rs
=> Drop `Storage` abstraction, revise fs cleanup logic for round reset

phase1-coordinator/src/coordinator.rs, phase1-coordinator/src/coordinator_state.rs, phase1-coordinator/src/tests.rs
=> Add logic to rollback locked tasks for a contributor

phase1-coordinator/src/commands/aggregation.rs, phase1-coordinator/src/commands/mod.rs, phase1-coordinator/src/coordinator.rs, phase1-coordinator/src/objects/contribution.rs, phase1-coordinator/src/objects/round.rs, phase1-coordinator/src/storage/disk.rs, phase1-coordinator/src/storage/storage.rs, phase1-coordinator/src/tests.rs
exploring potential solution to #359
Still currently a work in progress, does not compile yet.
=> Refactor to reduce memory consumption of memmap

phase1-coordinator/src/storage/disk.rs
=> Ensure state.json is not inadvertently deleted during round reset

phase1-coordinator/src/environment.rs
=> Modify drop timeouts to be configurable

phase1-coordinator/src/storage/disk.rs
=> Don't return errors or halt on failure during clear_round_files

phase1-coordinator/src/coordinator.rs, phase1-coordinator/src/coordinator_state.rs, phase1-coordinator/src/environment.rs, phase1-coordinator/src/tests.rs
=> Implement heartbeat mechanism for queued participants

phase1-coordinator/src/coordinator.rs, phase1-coordinator/src/coordinator_state.rs
=> Update queue ordering to be based on time joined

setup1-contributor/src/commands/contribute.rs
=> Ensure contributor will retry chunk uploads in case of network issues

phase1-coordinator/src/coordinator_state.rs, setup1-contributor/src/commands/contribute.rs, setup1-shared/src/structures.rs
=> Add queue position to progress bar for contributor

phase1-coordinator/src/coordinator.rs
=> Ensure that the round storage is updated when tasks are rolled back

phase1-coordinator/src/coordinator.rs, phase1-coordinator/src/coordinator_state.rs, phase1-coordinator/src/tests.rs
=> Add logic to undo a completed, unverified chunk

setup1-contributor/src/commands/contribute.rs
=> Add retry loop to queue joining logic

Cargo.lock, setup1-contributor/Cargo.toml, setup1-contributor/src/commands/contribute.rs, setup1-contributor/src/reliability/cpu.rs
Pinned the `tokio-tungstenite` revision and enabled `native-tls` feature
=> Fixed WebSockets handshake in contributor

phase1-coordinator/src/coordinator.rs, phase1-coordinator/src/tests.rs
=> Fix chunk unlock endpoint

setup1-contributor/src/commands/contribute.rs
=> Remove EOF capture and instead accept a phrase to advance to next stage

Cargo.lock, phase1-cli/Cargo.toml, phase1-cli/src/bin/phase1.rs, phase1-cli/src/bin/prepare_phase2.rs, phase1-coordinator/Cargo.toml, phase1-wasm/Cargo.toml, phase2/Cargo.toml, setup-utils/Cargo.toml, setup1-cli-tools/Cargo.toml, setup1-contributor/Cargo.toml, setup1-contributor/src/commands/contribute.rs, setup1-contributor/src/setup_keys/mod.rs, setup1-shared/Cargo.toml, setup1-verifier/Cargo.toml, setup2/Cargo.toml, setup2/src/main.rs
This updates all dependencies except for `rand 0.7` which is required by `age`.
=> Update dependencies 

Cargo.lock, phase1-coordinator/Cargo.toml, phase1-coordinator/src/commands/aggregation.rs, phase1-coordinator/src/commands/verification.rs, phase1-coordinator/src/coordinator.rs, phase1-coordinator/src/coordinator_state.rs, phase1-coordinator/src/environment.rs, phase1-coordinator/src/objects/round.rs, phase1-coordinator/src/testing/coordinator.rs, phase1-coordinator/src/testing/resources/round.json, phase1-coordinator/src/testing/resources/test_round_0.json, phase1-coordinator/src/testing/resources/test_round_1_initial.json, phase1-coordinator/src/testing/resources/test_round_1_partial.json, phase1-coordinator/src/tests.rs
=> Revert "Revert "Remove the dependency on `chrono`""
